apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: powerfulfamily-blog
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: powerfulfamily-blog-image=ghcr.io/masebb/powerfulfamily.net:latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/powerfulfamily-blog-image.update-strategy: digest
spec:
  project: default
  source:
    repoURL: 'https://github.com/masebb/powerfulfamily.net.git'
    targetRevision: HEAD
    path: manifest/
    kustomize: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: powerfulfamily
  syncPolicy:
    syncOptions:
      - Prune=true
      - CreateNamespace=true
    automated: {}
