apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerfulfamily-deployment
  labels:
    app: powerfulfamily
spec:
  replicas: 2
  selector:
    matchLabels:
      app: powerfulfamily
  template:
    metadata:
      labels:
        app: powerfulfamily
    spec:
      containers:
      - name: powerfulfamily
        image: ghcr.io/masebb/powerfulfamily.net:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: powerfulfamily
  name: powerfulfamily
  annotations:
    #metallb.universe.tf/loadBalancerIPs: 202.226.4.163,2403:bd80:c000:1600::a:3
spec:
  selector:
    app: powerfulfamily
  ports:
    - targetPort: http
      port: 80
