apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: powerfulfamily-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: powerfulfamily
                port:
                  number: 80
            path: /
            pathType: Prefix
