apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: powerfulfamily-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: powerfulfamily-nginx
  tls:
    - hosts:
      - powerfulfamily.net
      - www.powerfulfamily.net
      secretName: letsencrypt-prod-powerfulfamily-blog
  rules:
    - host: powerfulfamily.net
      http:
        paths:
          - backend:
              service:
                name: powerfulfamily-blog
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: www.powerfulfamily.net
      http:
        paths:
          - backend:
              service:
                name: powerfulfamily-blog
                port:
                  number: 80
            path: /
            pathType: Prefix
---
# Lets Encrypt Prod発行局
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: powerfulfamily
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: powerfulfamily-nginx
