apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: powerfulfamily-ingress
  cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: external-nginx
  tls:
    - hosts:
        - powerfulfamily.net
      secretName: letsencrypt-prod-powerfulfamily-net
  rules:
    - host: powerfulfamily.net
      http:
        paths:
          - backend:
              service:
                name: powerfulfamily
                port:
                  number: 80
            path: /
            pathType: Prefix
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod-powerfulfamily-net
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-powerfulfamily-net
    solvers:
      - http01:
          ingress:
            ingressClassName: external-nginx
